import json
import ast
import io
import sys
from src.database.Database import TrmericDatabase
# from src.trmeric_services.tango.utils.FormatJsonifiedData import formatSQLData
from src.utils.FormatJsonifiedData import formatSQLData
from src.trmeric_services.tango.types.TangoConversation import TangoConversation
# from src.ml.embeddings.VectorSearch import TrmericVectorSearch
from src.ml.llm.Client import LLMClient
import src.trmeric_services.tango.functions.Types
from src.trmeric_services.tango.functions.IntegrationRetriever import IntegrationRetriever
from src.trmeric_services.tango.types.TangoIntegration import TangoIntegration
from src.trmeric_services.tango.functions.Types import TangoFunction
import traceback

class Executor:
    def __init__(
        self,
        currentConversation: TangoConversation,
        database: TrmericDatabase,
        llm: LLMClient,
        userId,
        tenantId,
        integrations: list[TangoIntegration],
        eligibleFunctions: list[TangoFunction],
        actual_user_message="",
        socketio=None, 
        client_id=None
    ):
        self.currentConversation = currentConversation
        self.database = database
        self.llm = llm
        self.userId = userId
        self.tenantId = tenantId
        self.variables = {}  # To store variables and their values
        self.integrations = integrations
        self.eligibleFunctions = eligibleFunctions
        self.integrationRetriever = IntegrationRetriever(integrations)
        self.actual_user_message = actual_user_message
        self.socketio = socketio
        self.client_id = client_id

    def execute(self, llmResponse):
        """Parses the llm response and executes each of the statements

        Args:
            llmResponse (str): The response from the LLM, which could be multiple lines with function calls spanning multiple lines in odd cases
        """
        self.currentConversation.add_tango_code(llmResponse)
        data = []
        try:
            data = self.run(llmResponse)
        except Exception as e:
            print("debug this exception ", traceback.format_exc())
            data.append(f"Error executing code: {e} ")
        return data

    def run(self, code):
        """Given some code generated by the LLM, this function will first parse the code then find the matching available function.
        Then, it will call the function with the arguments provided in the code and return the result.

        Args:
            code (str): the code that the user wants to run, populated with whatever parameters they may want.

        Returns:
            The result is the data that the function will return.
        """
        print("run ------ ", code)

        # Parse the code to handle multi-line and variable assignments
        tree = ast.parse(code, mode="exec")
        # Execute each node in the AST
        results = []
        for node in tree.body:
            if isinstance(node, ast.Assign):
                # Handle variable assignment
                var_name = node.targets[0].id
                value = self.evaluate_expression(node.value)
                self.variables[var_name] = value
            elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
                # Handle function calls
                result = self.call_function(node.value)
                self.currentConversation.add_tango_data(result)
                results.append(result)
            else:
                raise ValueError("Unsupported code structure")
        # go through each result and print the type that it is 
        for result in results:
            results = "\n".join(results)
        return results

    def evaluate_expression(self, expr):
        """Evaluates an expression and returns its value."""
        if isinstance(expr, ast.Constant):
            return expr.value
        elif isinstance(expr, ast.Name):
            return self.variables.get(expr.id)
        elif isinstance(expr, ast.BinOp):
            left = self.evaluate_expression(expr.left)
            right = self.evaluate_expression(expr.right)
            if isinstance(expr.op, ast.Add):
                return left + right
            # Add more operators if needed
        else:
            raise ValueError("Unsupported expression type")

    def call_function(self, call):
        """Calls a function based on the provided AST Call node."""
        function_name = call.func.id
        # this is the function the model wants to call
        function = next((f for f in self.eligibleFunctions if f.name == function_name), None)
        if not function:
            raise ValueError("Function not found in available functions")
        if function.active:
            print("Executing an actionable function - be cautious")

        args = {}
        for arg in call.keywords:
            key = arg.arg
            if isinstance(arg.value, ast.Dict):
                args[key] = {k.s: v.s for k, v in zip(arg.value.keys, arg.value.values)}

            elif isinstance(arg.value, ast.List):
                args[key] = []
                for elt in arg.value.elts:
                    if isinstance(elt, ast.Str):
                        try:
                            # Try parsing the string as JSON
                            parsed_json = json.loads(elt.s)
                            if isinstance(parsed_json, dict):
                                args[key].append(parsed_json)  # Add parsed JSON dictionary to the list
                            else:
                                args[key].append(elt.s)  # If not a JSON object, add the raw string
                        except json.JSONDecodeError:
                            args[key].append(elt.s)  # If not a JSON string, add the raw string

                    elif isinstance(elt, ast.Num):
                        args[key].append(str(elt.n))  # Convert number elements to strings

                    elif isinstance(elt, ast.Dict):
                        # Handle if the element is a dictionary (JSON-like structure)
                        args[key].append({k.s: v.s for k, v in zip(elt.keys, elt.values)})

                    else:
                        pass

            elif isinstance(arg.value, ast.Str):
                try:
                    # Try parsing the string as JSON
                    parsed_json = json.loads(arg.value.s)
                    if isinstance(parsed_json, dict):
                        args[key] = parsed_json  # Store parsed JSON dictionary
                    else:
                        args[key] = arg.value.s  # If not a JSON object, store the raw string
                except json.JSONDecodeError:
                    args[key] = arg.value.s  # If not a JSON string, store the raw string

            elif isinstance(arg.value, ast.Name):
                args[key] = self.variables.get(arg.value.id)

            elif isinstance(arg.value, ast.Constant):
                # Handle None, Boolean, or other constant values
                if arg.value.value is None:  # Check if the value is None
                    args[key] = None
                elif isinstance(arg.value.value, bool):  # Handle booleans
                    args[key] = arg.value.value
                elif isinstance(arg.value.value, (int, float)):  # Handle numbers
                    args[key] = arg.value.value  # Directly store ints or floats

            elif isinstance(arg.value, ast.NameConstant):
                if arg.value.value is None:  # Check if the value is None
                    args[key] = None
                elif isinstance(arg.value.value, bool):  # Handle booleans
                    args[key] = arg.value.value

            else:
                pass

            
        integration = self.integrationRetriever.getIntegration(function.integration)
        
        if integration.name == "trmeric" or integration.name == "general":
            args['tenantID'] = self.tenantId
            args['userID'] = self.userId 
            args['eligibleProjects'] = integration.eligibleProjects
            # args["socketio"] = self.socketio
            # args["client_id"] = self.client_id
            # args["actual_user_message"] = self.actual_user_message
            # args['llm'] = self.llm
            if function.name == "specific_project_creation" or function.name == "specific_roadmap_creation" or function.name == "specific_profile_creation":
                args['userID'] = self.userId
                args['integrations'] = self.integrations
                args['llm'] = self.llm
            result = function.function(**args)
        else:
            args['api'] = integration.api
            result = function.function(**args)

        print("Done with function: ", function_name)
        
        # Format the result for better readability
        result = f"------START OF DATA RETRIEVED FROM {function.integration}------\n{result}\n------END OF DATA RETRIEVED FROM {function.integration}------"
        
        return result


    # def call_function(self, call):
    #     """Calls a function based on the provided AST Call node."""
    #     function_name = call.func.id
    #     # this is the function the model wants to call
    #     function = next((f for f in self.eligibleFunctions if f.name == function_name), None)
    #     if not function:
    #         raise ValueError("Function not found in available functions")
    #     if function.active:
    #         print("Executing an actionable function - be cautious")
    #     args = {}
    #     for arg in call.keywords:
    #         key = arg.arg
    #         if isinstance(arg.value, ast.Dict):
    #             args[key] = {k.s: v.s for k, v in zip(
    #                 arg.value.keys, arg.value.values)}
    #         elif isinstance(arg.value, ast.List):
    #             if isinstance(arg.value.elts[0], ast.List):
    #                 args[key] = [
    #                     [elt.s if isinstance(elt, ast.Str) else elt.n for elt in innerList.elts] for innerList in arg.value.elts
    #                 ]
    #             else:
    #                 args[key] = [
    #                     elt.s if isinstance(elt, ast.Str) else elt.n for elt in arg.value.elts if isinstance(elt, (ast.Str, ast.Num))
    #                 ]
    #         elif isinstance(arg.value, ast.Str):
    #             # Handle string arguments
    #             args[key] = arg.value.s
    #         elif isinstance(arg.value, ast.Name):
    #             # Handle variable arguments
    #             args[key] = self.variables.get(arg.value.id)
    #         else:
    #             pass
    #     integration = self.integrationRetriever.getIntegration(function.integration)
        
        
    #     if integration.name == "trmeric" or integration.name == "general":
    #         args['tenantID'] = self.tenantId
    #         args['eligibleProjects'] = integration.eligibleProjects
    #         result = function.function(**args)
    #     else:
    #         args['api'] = integration.api
            
    #         result = function.function(**args)
    #     print ("Done with function: ", function_name)
    #     result = "------START OF DATA RETRIEVED FROM " + function.integration + "------\n" + result + "\n------END OF DATA RETRIEVED FROM " + function.integration + "------"
    #     return result

    
