
### DB KEYS USED
AGENT_INITIATE_SWITCH_OCCURED = "AGENT_INITIATE_SWITCH_OCCURED"
CURRENT_ACTIVE_AGENT = "CURRENT_ACTIVE_AGENT"


## AGENT NAMES 
ORION_ID = "orion"
ORION_PLANNING = "orion_planning"
ORION_SOLUTIONING = "orion_solutioning"