from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional
from .privacy_models import PrivacyScope


@dataclass
class QueryPlan:
    """
    Structured query plan generated by LLM intent detection.
    
    This dataclass ensures type safety and makes it explicit what
    information is needed to execute a graph query.
    """
    
    # Core query components
    vertices_to_query: List[str] = field(default_factory=list)
    edges_to_query: List[str] = field(default_factory=list)
    entity_ids: List[str] = field(default_factory=list)  # project_ids, roadmap_ids, etc.
    
    # Attribute filtering
    attributes_to_query: Dict[str, List[str]] = field(default_factory=dict)
    
    # Dynamic filters (e.g., {"Technology": {"name": "React"}})
    filters: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    
    # Privacy and access control
    privacy_scope: PrivacyScope = PrivacyScope.PRIVATE
    
    # Clarification handling
    clarification_needed: bool = False
    clarification_message: Optional[str] = None
    
    # Metadata
    planning_rationale: str = ""
    entity_type: str = ""  # "Project", "Roadmap", etc.
    
    def is_valid(self) -> bool:
        """Check if the query plan has minimum required information"""
        if self.clarification_needed:
            return False
        return bool(self.vertices_to_query or self.entity_ids)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for logging/debugging"""
        return {
            "vertices_to_query": self.vertices_to_query,
            "edges_to_query": self.edges_to_query,
            "entity_ids": self.entity_ids,
            "attributes_to_query": self.attributes_to_query,
            "filters": self.filters,
            "privacy_scope": self.privacy_scope.value,
            "clarification_needed": self.clarification_needed,
            "clarification_message": self.clarification_message,
            "planning_rationale": self.planning_rationale,
            "entity_type": self.entity_type,
        }
