"""api integration start 2

Revision ID: 2d0206d8a3c8
Revises: f65be7fe586a
Create Date: 2026-03-29 17:32:19.641011+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '2d0206d8a3c8'
down_revision: Union[str, None] = 'f65be7fe586a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('de_connections',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('de_schema_snapshots',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semantic_layer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['de_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('de_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['de_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('de_runs',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('connection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('queries_executed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chart_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sheet_s3_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['de_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['de_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('de_runs')
    op.drop_table('de_sessions')
    op.drop_table('de_schema_snapshots')
    op.drop_table('de_connections')
    # ### end Alembic commands ###
