"""add dao config tables mistake earlier

Revision ID: f0aa13a33554
Revises: 60de18ef87ca
Create Date: 2026-03-29 15:02:36.783232+00:00

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = 'f0aa13a33554'
down_revision: Union[str, None] = '60de18ef87ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dao_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('attr_name', sa.Text(), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('table_alias', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id_field', sa.Text(), nullable=True),
    sa.Column('base_where', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('where_extra', sa.Text(), nullable=True),
    sa.Column('joins', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('group_by', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dao_attribute_hooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=True),
    sa.Column('hook_type', sa.Text(), nullable=True),
    sa.Column('hook_name', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['dao_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dao_field_intel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('column_name', sa.Text(), nullable=True),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['dao_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dao_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('sql_expression', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attr_id'], ['dao_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dao_fields')
    op.drop_table('dao_field_intel')
    op.drop_table('dao_attribute_hooks')
    op.drop_table('dao_attributes')
    # ### end Alembic commands ###
