class TangoConversation:

    def __init__(self, user_id: str, session_id: str, tenant_id: str):
        self.conversation = []
        self.user_id = user_id
        self.session_id = session_id
        self.tenant_id = tenant_id
        self.summary = None

    def add_user_message(self, message: str, timestamp: str):
        """
        Adds a user message to the conversation.

        Args:
            message (str): The user message to add to the conversation.
        """
        self.conversation.append(
            {
                "user": message,
                "tango": None,
                "timestamp": timestamp,
                "data": None,
                "code": None,
            }
        )

    def add_tango_code(self, code='', timestamp= ''):
        """
        Adds a tango code to the conversation.

        Args:
            code (str): The tango code to add to the conversation.
        """
        try:
            self.conversation[-1]["code"] = code
        except Exception as e:
            self.conversation.append(
                {
                    "user": '',
                    "tango": None,
                    "timestamp": timestamp,
                    "data": None,
                    "code": None,
                }
            )
            self.conversation[-1]["code"] = code

    def add_tango_data(self, data):
        """
        Adds tango data to the conversation.

        Args:
            data (str): The tango data to add to the conversation.
        """
        self.conversation[-1]["data"] = data

    def add_tango_message(self, message):
        """
        Adds a tango message to the conversation.

        Args:
            message (str): The tango message to add to the conversation.
        """
        self.conversation[-1]["tango"] = message
        
    def add_summary(self, summary):
        """
        Adds a summary to the conversation.

        Args:
            summary (str): The summary to add to the conversation.
        """
        self.summary = summary
        
    def last_tango_message(self):
        """
        Returns the last tango message in the conversation.

        Returns:
            str: The last tango message in the conversation.
        """
        for message in reversed(self.conversation):
            if message["tango"]:
                return message["tango"]
        return None
    
    def last_user_message(self):
        """
        Returns the last user message in the conversation.

        Returns:
            str: The last user message in the conversation.
        """
        for message in reversed(self.conversation):
            if message["user"]:
                return message["user"]
        return None

    def format_conversation(self, name="Tango") -> str:
        recent_messages = self.conversation[-4:]
        formatted_messages = []
        formatted_messages.append("-----------Start of Messages---------")
        if self.summary:
            formatted_messages.append(f"\n\nHere is a summary of the ongoing chat with user. You have been provided recent chats but the summary includes what you and the user have spoken about further above: {self.summary} \n")
        
        formatted_messages.append("You are about to see recent messages with the most recent information at the bottom, followed by a summary of what has occured previously.\n")
        for message in recent_messages:
            formatted_message = f"User: {message['user']}"
            if message["data"]:
                formatted_message += (
                    f"\nData Retrieved by {name} Response: {message['data']}"
                )
            if message["code"]:
                formatted_message += (
                    f"\nCode/Thought Generated by {name}: {message['code']}"
                )
            if message["tango"]:
                formatted_message += f"\n {name}: {message['tango']}"
            formatted_messages.append(formatted_message)
            formatted_messages.append('\n\n')
        formatted_messages.append("-----------End of Messages---------")
        return "\n".join(formatted_messages)

    def format_conversation_simple(self) -> str:
        formatted_messages = []
        formatted_messages.append("-----------Start of Messages---------")
        formatted_messages.append("You are about to see a series of user queries and Tango responses that have occured previously.\n")
        for message in self.conversation:
            formatted_messages.append('-----------------------------------')
            formatted_message = f"User: {message['user']}"
            if message["tango"]:
                formatted_message += f"\n Tango Response: {message['tango']}"
            formatted_messages.append(formatted_message)
            formatted_messages.append('-----------------------------------')
            formatted_messages.append('\n\n')
        formatted_messages.append("-----------End of Messages---------")
        return "\n".join(formatted_messages)
